name: 'Test Kratix'
description: 'The Unit, System and Integration tests'
inputs:
  sha:  # id of input
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: syntasso/kratix
        ref: ${{ github.event.inputs.sha }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
        check-latest: true
    - name: Unit Tests
      shell: bash
      run: |
        make test
