name: 'Test Kratix'
description: 'The Unit, System and Integration tests'
inputs:
  sha:  # id of input
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: syntasso/kratix
        ref: ${{ github.event.inputs.sha }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
        check-latest: true
    - name: Unit Tests
      run: |
        make test
    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.63.4
        ./bin/golangci-lint run --config=.golangci-required.yml
